/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Ravindu
 */
public class OptionPaneAddedSuccess extends javax.swing.JDialog {

    /**
     * Creates new form OPtionFrmae
     *
     * @param parent
     * @param modal
     * @param jf
     * @param tittle
     */
    public OptionPaneAddedSuccess(java.awt.Frame parent, boolean modal, String tittle) {
        super(parent, modal);
        initComponents();
        setAlwaysOnTop(true);
        setLocationRelativeTo(null);

        lblTitle.setText(tittle);
        setVisible(true);
        lblTitle.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCloseBt = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(null);

        lblCloseBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/close.png"))); // NOI18N
        lblCloseBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseExited(evt);
            }
        });
        jPanel1.add(lblCloseBt);
        lblCloseBt.setBounds(320, 0, 30, 30);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("                 Added Success...!");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(47, 26, 270, 51);

        btnOk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Ok");
        btnOk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel1.add(btnOk);
        btnOk.setBounds(130, 80, 79, 25);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1, 1, 350, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseBtMouseClicked

    private void lblCloseBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseEntered
        lblCloseBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/closeFill.png"));
    }//GEN-LAST:event_lblCloseBtMouseEntered

    private void lblCloseBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseExited
        lblCloseBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/close.png"));
    }//GEN-LAST:event_lblCloseBtMouseExited

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OPtionFrmae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OPtionFrmae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OPtionFrmae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OPtionFrmae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                OPtionFrmae dialog = new OPtionFrmae(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCloseBt;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
